import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        red: "#FF0000",
        bone: "#FAF6E7",
        black: "#000000",
        white: "#FFFFFF",
        "dark-red": "#CC0000",
      },
      fontFamily: {
        obviously: ["Obviously", "sans-serif"],
        "obviously-narrow": ["Obviously Narrow", "sans-serif"],
        "obviously-wide": ["Obviously Wide", "sans-serif"],
        "tiempos-text": ["Tiempos Text", "serif"],
        "tiempos-headline": ["Tiempos Headline", "serif"],
        "tiempos-fine": ["Tiempos Fine", "serif"],
      },
      spacing: {
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        xl: "48px",
        "2xl": "64px",
        "3xl": "96px",
        "4xl": "128px",
      },
      borderRadius: {
        button: "8px",
        card: "8px",
        pill: "20px",
        none: "0px",
      },
      maxWidth: {
        narrow: "600px",
        content: "800px",
        standard: "900px",
        wide: "1000px",
        full: "1100px",
      },
      fontSize: {
        h1: ["72px", { lineHeight: "1.0" }],
        "h1-mobile": ["40px", { lineHeight: "1.0" }],
        h2: ["48px", { lineHeight: "1.1" }],
        "h2-mobile": ["32px", { lineHeight: "1.1" }],
        h3: ["32px", { lineHeight: "1.2" }],
        "h3-mobile": ["24px", { lineHeight: "1.2" }],
        h4: ["24px", { lineHeight: "1.3" }],
        "h4-mobile": ["20px", { lineHeight: "1.3" }],
        h5: ["14px", { lineHeight: "1.4" }],
        "h5-mobile": ["12px", { lineHeight: "1.4" }],
        h6: ["12px", { lineHeight: "1.4" }],
        "h6-mobile": ["11px", { lineHeight: "1.4" }],
        "body-lg": ["20px", { lineHeight: "1.6" }],
        "body-lg-mobile": ["18px", { lineHeight: "1.6" }],
        "body": ["18px", { lineHeight: "1.6" }],
        "body-mobile": ["16px", { lineHeight: "1.6" }],
        "body-sm": ["16px", { lineHeight: "1.5" }],
        "body-sm-mobile": ["14px", { lineHeight: "1.5" }],
        caption: ["13px", { lineHeight: "1.4" }],
        "caption-mobile": ["12px", { lineHeight: "1.4" }],
        "pull-quote": ["28px", { lineHeight: "1.4" }],
        "pull-quote-mobile": ["22px", { lineHeight: "1.4" }],
        "stat": ["64px", { lineHeight: "1.0" }],
        "stat-mobile": ["40px", { lineHeight: "1.0" }],
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
export default config;
